### ISSUE TITLE
What is the difference between W25QXX_INTERFACE_SPI and W25QXX_INTERFACE_QSPI

### ISSUE THREAD

**Issue by IOL0ol1** [libdriver/w25qxx#18]
### Please ask your question

Machine translated into English, if you can understand, please read the last Chinese directly :).
It's a great project. 
What do the combinations of **dual_quad_spi_enable** and **spi_qspi** mean?
I'm using the Microchip code generation tool to generate the qspi code for SAMD51P20A(arm M4) like this:
[plib_qspi.zip](https://github.com/user-attachments/files/16104225/plib_qspi.zip)

my **w25qxx_handle_t.spi_qspi_write_read**  like this

```
uint8_t w25qxx_spi_qspi_write_read(uint8_t instruction, uint8_t instruction_line,
uint32_t address, uint8_t address_line, uint8_t address_len,
uint32_t alternate, uint8_t alternate_line, uint8_t alternate_len,
uint8_t dummy, uint8_t *in_buf, uint32_t in_len,
uint8_t *out_buf, uint32_t out_len, uint8_t data_line)
{
	QSPI_LANE_WIDTH width = SINGLE_BIT_SPI; 
	QSPI_ADDRESS_LENGTH addr_len = address_len == 4?ADDRL_32_BIT:ADDRL_24_BIT;
	QSPI_OPTION_LENGTH option_len = 0;
	
	if(instruction_line == 4) width = QUAD_CMD; /* (QSPI_INSTRFRAME) Instruction: Quad SPI / Address-Option: Quad SPI / Data: Quad SPI Position  */
	else if(instruction_line == 2) width = DUAL_CMD; /* (QSPI_INSTRFRAME) Instruction: Dual SPI / Address-Option: Dual SPI / Data: Dual SPI Position  */
	else if(address_line == 4) width = QUAD_IO; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Quad SPI / Data: Quad SPI Position  */
	else if(address_line == 2) width = DUAL_IO; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Dual SPI / Data: Dual SPI Position  */
	else if(data_line == 4) width = QUAD_OUTPUT; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Single-bit SPI / Data: Quad SPI Position  */
	else if(data_line == 2) width = DUAL_OUTPUT; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Single-bit SPI / Data: Dual SPI Position  */
	else width = SINGLE_BIT_SPI; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Single-bit SPI / Data: Single-bit SPI Position  */

	if(alternate_len == 1) option_len = OPTL_1_BIT;
	else if(alternate_len == 2) option_len = OPTL_2_BIT;
	else if(alternate_len == 4) option_len = OPTL_4_BIT;
	else if(alternate_len == 8) option_len = OPTL_8_BIT;
	else option_len = 0;
	
	if(out_buf == NULL && in_buf == NULL)
	{
		qspi_command_xfer_t qspi_command_xfer;
		qspi_command_xfer.instruction = instruction;
		qspi_command_xfer.width = width;
		qspi_command_xfer.addr_len = addr_len;
		qspi_command_xfer.addr_en = address_len != 0;
		return (uint8_t)!QSPI_CommandWrite(&qspi_command_xfer,address);
	}
	if(out_buf != NULL && address_len == 0)
	{
		qspi_register_xfer_t qspi_register_xfer;
		qspi_register_xfer.instruction = instruction;
		qspi_register_xfer.dummy_cycles = dummy;
		qspi_register_xfer.width = width;
		return (uint8_t)!QSPI_RegisterRead(&qspi_register_xfer,(uint32_t*)out_buf,(uint8_t)out_len);
	}
	if(in_buf != NULL && address_len == 0)
	{
		qspi_register_xfer_t qspi_register_xfer;
		qspi_register_xfer.instruction = instruction;
		qspi_register_xfer.dummy_cycles = dummy;
		qspi_register_xfer.width = width;
		return (uint8_t)!QSPI_RegisterWrite(&qspi_register_xfer,(uint32_t*)in_buf,(uint8_t)in_len);
	}
	
	if(out_buf != NULL && address_len != 0)
	{
		qspi_memory_xfer_t qspi_memory_xfer;
		qspi_memory_xfer.instruction = instruction;
		qspi_memory_xfer.dummy_cycles = dummy;
		qspi_memory_xfer.width = width;
		qspi_memory_xfer.addr_len = addr_len;
		qspi_memory_xfer.option = alternate;
		qspi_memory_xfer.option_en = alternate_len != 0;
		qspi_memory_xfer.option_len = option_len;
		return (uint8_t)!QSPI_MemoryRead(&qspi_memory_xfer,(uint32_t*)out_buf,out_len,address);
	}
	if(in_buf != NULL && address_len != 0)
	{
		qspi_memory_xfer_t qspi_memory_xfer;
		qspi_memory_xfer.instruction = instruction;
		qspi_memory_xfer.dummy_cycles = dummy;
		qspi_memory_xfer.width = width;
		qspi_memory_xfer.addr_len = addr_len;
		qspi_memory_xfer.option = alternate;
		qspi_memory_xfer.option_en = alternate_len != 0;
		qspi_memory_xfer.option_len = option_len;
		return (uint8_t)!QSPI_MemoryWrite(&qspi_memory_xfer,(uint32_t*)in_buf,in_len,address);
	}
	return 1;
}
```
Do you want to achieve a **QSPI_LANE_WIDTH** like function through a combination of **dual_quad_spi_enable** and **spi_qspi**?
If so, can we use the combination of **instruction_line** , **address_len**, **data_line** to switch spi, dspi, qspi in **spi_qspi_write_read**, because now there are basically three sets of branch codes for switching spi, dspi, and qspi in each function, if they are unified in **spi_qspi_write_read** switching, Will the compiled binary be more streamlined?
If there is a deviation in my understanding, please correct it, thank you.

机翻英文比较拉跨，补充中文 
很棒的项目，啊哈:) 
代码中的 **dual_quad_spi_enable** 和 **spi_qspi** 的组合怎么理解？
我使用的是Microchip的代码生成器为SAMD51P20A(arm M4)生成的qspi代码，详见上文 附件压缩包plib_qspi.zip。
然后我实现的 **w25qxx_handle_t.spi_qspi_write_read** 详见上文代码。
你是想通过 **dual_quad_spi_enable** 和 **spi_qspi** 的组合来实现类似 **QSPI_LANE_WIDTH** 的功能吗?
如果是这样，我们是不是可以通过 instruction_line ,address_len, data_line 的组合统一在 **spi_qspi_write_read** 切换 spi,dspi,qspi, 因为现在每个函数中基本都有三套切换spi,dspi,qspi的分支代码，如果统一在 **spi_qspi_write_read** 切换，编译之后的二进制是不是会更精简?
如果我理解的有偏差，欢迎指正，谢谢。

### Additional context

关键是这里, 我把plib_qspi的注释抄过来了。
```
	if(instruction_line == 4) width = QUAD_CMD; /* (QSPI_INSTRFRAME) Instruction: Quad SPI / Address-Option: Quad SPI / Data: Quad SPI Position  */
	else if(instruction_line == 2) width = DUAL_CMD; /* (QSPI_INSTRFRAME) Instruction: Dual SPI / Address-Option: Dual SPI / Data: Dual SPI Position  */
	else if(address_line == 4) width = QUAD_IO; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Quad SPI / Data: Quad SPI Position  */
	else if(address_line == 2) width = DUAL_IO; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Dual SPI / Data: Dual SPI Position  */
	else if(data_line == 4) width = QUAD_OUTPUT; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Single-bit SPI / Data: Quad SPI Position  */
	else if(data_line == 2) width = DUAL_OUTPUT; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Single-bit SPI / Data: Dual SPI Position  */
	else width = SINGLE_BIT_SPI; /* (QSPI_INSTRFRAME) Instruction: Single-bit SPI / Address-Option: Single-bit SPI / Data: Single-bit SPI Position  */
```

**Comment by libdriver** [comment]
Thank you very much for using LibDriver and give us the feedback.

W25QXX supports SPI, QSPI, and SPI derived interface.

We use "spi_qspi" to distinguish the current hardware interface, many QSPI operations may not be supported by SPI, and QSPI operations are not fully supported,Even the same QSPI and SPI operations are not exactly the same. Distinguishing different interfaces through spi_qspi ensures the correctness of program operation. Many hardware devices do not support QSPI, but most support SPI and even can simulate SPI through GPIO. In this case, "spi_qspi_write.read" is actually only effective for the part of input and output. If any of the other parts is meaningful and should return an error, and you can refer to ./ project/stm32f407/driver/src/stm32f407_driver_w25qxx_interface.c

The use of "dual_quad_spi_enable" is to distinguish between standard SPI and SPI derived interface.Such as "w25qxx_get_manufactor_device_id_dual_io",both SPI and SPI derived interface are supported, but QSPI is not supported. SPI derived interfaces can't be implemented by standard SPI interfaces, but can be implemented by QSPI interfaces. When doing such operations, if interface is QSPI, this driver will directly return an error because the chip does not support the current operation on this interface; If the hardware supports both QSPI and SPI, dual_quad_spi_enable can be set to true; if interface is SPI derived interface, it will be indirectly implemented through the QSPI interface; When the chip only supports SPI, dual_quad_spi_enable must be false because the standard SPI interface cannot implement SPI derived interfaces and cannot be executed the current operation.

W25QXX supports SPI, QSPI, and SPI derived interface. Most hardware does not support QSPI, considering the compatibility of SPI interfaces and the differences of interfaces for the same instruction on the chip, We use the current programming architecture.

非常感谢您使用LIbDriver并给我们提出宝贵意见。

W25QXX同时支持SPI、QSPI和类SPI衍生接口。

使用“spi_qspi ”为了区分当前使用的硬件接口，很多QSPI操作SPI可能并不支持，SPI的操作QSPI也并不完全支持，甚至同一个操作QSPI和SPI操作也不完全相同，通过spi_qspi区分不同接口，确保程序运行的正确性。很多的硬件并不支持QSPI，但是
大部分支持SPI，甚至可以通过GPIO软件模拟SPI，这种情况下“spi_qspi_write_read”实际上只有后面数据交互的部分是有效的，如果这个接口其他部分有意义，应该返回错误，您可以参考./project/stm32f407/driver/src/stm32f407_driver_w25qxx_interface.c

使用“dual_quad_spi_enable”是为了区分标准SPI和类SPI衍生接口，很多的操作比如"w25qxx_get_manufacturer_device_id_dual_io"同时支持SPI和类SPI衍生接口但是不支持QSPI，SPI衍生接口使用标准的SPI接口无法实现，其本质是使用QSPI接口实现的。当请求这类操作时，如果是QSPI接口会直接返回错误，因为芯片该接口不支持当前操作；如果硬件既支持QSPI也支持SPI，可以把dual_quad_spi_enable设置为true；当通过类SPI衍生接口执行该操作时，会间接的通过QSPI接口实现；当芯片只支持SPI，dual_quad_spi_enable必须为false，因为标准的SPI接口无法实现类SPI衍生接口，无法执行当前操作。

W25QXX同时支持SPI、QSPI和类SPI衍生接口，大部分硬件不支持QSPI，考虑SPI接口的兼容性、芯片同一指令不同接口差异性等，综合考虑设计当前的处理机制。
